### ISSUE TITLE
Unclear licensing

### ISSUE THREAD

**Issue by Millnert** [catalyst/catalystcloud-docs#22]
It's not clear what the licensing of this repository is. We're interested in a fork, but would in turn be willing to contribute back documentation that we add locally.

**Comment by mmmucky** [comment]
Hi Martin, I'll see if I can get that sorted.

**Comment by mmmucky** [comment]
We will be applying a Creative Commons Attribution-ShareAlike license to this content.  https://creativecommons.org/licenses/by-sa/4.0/

**Comment by donovan** [comment]
Hi Martin.

I have updated the README with the licence information (cc-by-sa-4.0). Looking forward to your contributions.

**Comment by Millnert** [comment]
Hi James, and Donovan,

great, looking forward to great success.
